---
- name: Omnia Networklist deployment steps
  hosts: all
  become: true
  tasks:
    - name: Install http-server.
      community.general.npm:
        name: http-server
        global: true

    - name: Create /opt/omnia-networklist/ if it does not exist
      file:
        path: /opt/omnia-networklist/
        state: directory
        mode: 0644

    - name: Compress directory static files before moving
      archive:
        path: ../../../out/
        dest: ./out.tar.gz

    - name: move and unarchive static files
      unarchive:
        src: ./out.tar.gz
        dest: /opt/omnia-networklist/

    - name: copy dashboard frontend service file
      copy:
        src: ../../networklist-frontend.service
        dest: /lib/systemd/system/

    - name: start dashboard-frontend service
      systemd:
        daemon_reload: yes
        name: networklist-frontend.service
        state: started
        enabled: yes
